### ISSUE TITLE
Convert from tagged tuples to exceptional

### ISSUE THREAD

**Issue by jcelliott** [expede/exceptional#2] opened 2016-09-12 03:28 UTC
I really like the error handling approach `exceptional` takes, but I do have a concern about it's practical use. It has support for converting from exceptions to tagged tuples via `to_tagged_status`, but is there a strategy for going the other direction? It seems like a pretty common scenario since most of the Elixir ecosystem currently uses tagged tuples. Your medium article definitely made the case for this style of error handling, but also glossed over this issue by using a "hypothetical rewrite of File.read". How have you dealt with this while using the library?

**Comment by expede** [comment] 2016-09-14 11:24
Hm, yes, I hear what you're saying! I've debated adding exactly that to the library, but decided against it. The problem is that `{:error, _}` is so generic that we don't have typically enough information to assign it to a particular Exception. Using some `GenericException` totally defeats the purpose aside from not having to deal with tuples all over the place.
I'm explicitly matching on tuples with a `case`.

**Comment by expede** [comment] 2016-09-14 12:00
...I suppose that we could add a matcher to the library for all of the common functions like `File.read` and so on 💭 However, this would still lead to many cases where you're not getting maximum context (`Enum.OutOfBoundsError` is less meaningful than `XML.Search.NoAttributeMatchError` in an XML-searching module). Might be worth adding for the convenience, though. I'll think on it. Any thoughts?

**Comment by jcelliott** [comment] 2016-09-14 20:45
> Also, some libs don't follow the {:error, String.t} convention

Yep, just ran into this with [Poison.decode](https://hexdocs.pm/poison/Poison.html#decode/2):

``` elixir
decode(iodata, Keyword.t) ::
  {:ok, Poison.Parser.t} |
  {:error, :invalid} |
  {:error, {:invalid, String.t}}
```

The only thought I had on that was that you could match *any* tuple where `:error = elem(tuple, 0)`. That doesn't buy you much, except that libraries could potentially return more information than a string error message: `{:error, :no_attribute_match, "didn't find an attribute 'foo'"}`, but at that point you might as well just use an exception...

I wrote some helpers to do the conversion, but quickly noticed all the issues you mentioned. I don't have any better answers right now, but I'll think about it some more.

Thanks for the great library in any case!

**Closed** 2016-09-15 15:12 UTC
Labels: question
